services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:9999"
    depends_on:
      - web-server-1
      - web-server-2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 25M

  web-server-1:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    container_name: fastapi-1
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 100M

  web-server-2:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    container_name: fastapi-2
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 100M

  workers:
    build:
      context: ./
      dockerfile: ./docker/worker/Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    networks:
      - default
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 105M

  redis:
    hostname: redis
    image: redis:alpine
    expose:
      - "6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 20M

networks:
  default:
    driver: bridge
  payment-processor:
    external: true
